name: Semantic Release

on:
  pull_request:
    types: [closed]
    branches:
      - main

jobs:
  release:
    runs-on: ubuntu-latest
    concurrency: release
    permissions:
      id-token: write
      contents: write

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.ACTION_TOKEN }}

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      - name: Install package for custom parser
        run: pip install -U pip && pip install -e .

      - name: Verify custom parser installation
        run: |
          python -c "import custom_parser; print('Custom parser loaded successfully')"

      - name: Apply versioning
        run: semantic-release version --no-vcs-release
        env:
          GH_TOKEN: ${{ secrets.ACTION_TOKEN }}
